task:
  auto_cancellation: $CIRRUS_BRANCH != 'master' || $CIRRUS_TAG != ''
  container:
    image: gradle:4.10.3-jdk8
    cpu: 4
    memory: 12G
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: cat build.gradle
    populate_script: gradle setupCiWorkspace --parallel
  name: Cirrus CI
  script: gradle build --parallel
  jar_artifacts:
    path: ./build/libs/**
  always:
    cleanup_before_cache_script: |
      rm -rf ~/.gradle/caches/$GRADLE_VERSION/ ~/.gradle/caches/transforms-1 ~/.gradle/caches/journal-1 ~/.gradle/caches/minecraft/deobfedDeps/compileDummy.jar ~/.gradle/caches/minecraft/deobfedDeps/providedDummy.jar
      find ~/.gradle/caches/ -name "*.lock" -type f -delete
